//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_Team1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangBuoiHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BangBuoiHoc()
        {
            this.DiemDanh = new HashSet<DiemDanh>();
        }
    
        public string maBH { get; set; }
        public string maKH { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public Nullable<System.TimeSpan> gio { get; set; }
        public string phong { get; set; }
        public Nullable<System.TimeSpan> gioBatDau { get; set; }
        public Nullable<System.TimeSpan> gioKetThuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemDanh> DiemDanh { get; set; }
        public virtual KhoaHoc KhoaHoc { get; set; }
    }
}
